### ISSUE TITLE
電話番号の修正

### ISSUE THREAD

**Issue by ishigami-prart** [ishigami-prart/grvenus#47]
@percent365

先方より電話番号の修正がきました。

■トップ予約フォームバナーの下

お電話でのご予約の場合は0263-50-7250（電話受付時間 8：00～20：00）までお願いします。
お急ぎの方はこちらへ 090-9667-1434

■お問い合わせフォーム

0263-50-7250　へ番号を変更
受付時間を記載
担当上條を消す

小さい文字で　お急ぎの方はこちらへ 090-9667-1434　をいれてください

全体的にバナーの隙間など調整してください

■プライバシーポリシー

一番したの電話番号を　0263-50-7250　へ変更
プライバシーポリシーのページ、お問い合わせ、予約フォームの三か所

**Comment by percent365** [comment]
先程の修正も含め修正致しました！

**Comment by ishigami-prart** [comment]
@percent365 
お問い合わせと予約ページのフォーム内のプライバシーポリシーの電話番号の修正もお願いできますか？

**Comment by percent365** [comment]
@ishigami-prart 
失礼いたしました。修正致しました！
