### ISSUE TITLE
ロゴ画像の差し替え

### ISSUE THREAD

**Issue by ishigami-prart** [ishigami-prart/grvenus#49]
@percent365
すみません、ロゴを制作した業者の方でスペル間違えがあったみたいで
ロゴの差し替えをお願いできますでしょうか。

誤りGRAMPING RESORT VENUS
正　GLAMPING RESORT VENUS

https://8.gigafile.nu/1102-bddab483d0a70ac026b46bd18e4c12a79

・ロード画面
・ヘッダー
・ヘッダー縮小時
・フッター
・ノーイメージ画像

お手数をおかけしますが、
よろしくお願いいたします。

**Comment by percent365** [comment]
@ishigami-prart 
動画・ロゴ修正いたしました。

**Comment by ishigami-prart** [comment]
@percent365
ヘッダーの縮小時のロゴが変わっていないようです。

動画がクロームだと途中で止まってしまうみたいで一度アップしなおしてみてもらってもよいでしょうか？

**Comment by ishigami-prart** [comment]
@percent365 

>動画がクロームだと途中で止まってしまうみたいで一度アップしなおしてみてもらってもよいでしょうか？
すみません、こちらは別の問題っぽいので実施しなくて大丈夫です。

**Comment by percent365** [comment]
@ishigami-prart 
![スクリーンショット 2024-10-28 14 11 25](https://github.com/user-attachments/assets/5e0bdbf3-801c-4adf-8ae4-c5934999acf7)
ここで合っていますか？
私の方だと変わっているのですが・・・
違う部分でしょうか？

**Comment by ishigami-prart** [comment]
@percent365
すみません、キャッシュっぽいです。
シークレットウィンドウでこちらでも確認できました！
